import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { test } from 'node:test';

const extensionRoot = path.resolve(__dirname, '..', '..', '..');

test('manifest registers Nemerle language, commands, settings, and restricted mode', () => {
  const manifest = readJson<Record<string, any>>('package.json');
  const language = manifest.contributes.languages[0];
  assert.equal(language.id, 'nemerle');
  assert.deepEqual(language.extensions, ['.n']);
  assert.equal(language.configuration, './language-configuration.json');

  const grammar = manifest.contributes.grammars[0];
  assert.equal(grammar.language, 'nemerle');
  assert.equal(grammar.scopeName, 'source.nemerle');
  assert.ok(fs.existsSync(path.join(extensionRoot, grammar.path)));

  const commands = new Set(
    manifest.contributes.commands.map((command: { command: string }) => command.command),
  );
  assert.ok(commands.has('nemerle.restartLanguageServer'));
  assert.ok(commands.has('nemerle.showOutput'));
  assert.ok(commands.has('nemerle.selectProject'));
  assert.ok(commands.has('nemerle.reloadProject'));
  assert.ok(commands.has('nemerle.showProjectStatus'));

  const properties = manifest.contributes.configuration.properties;
  assert.equal(properties['nemerle.server.path'].type, 'string');
  assert.deepEqual(properties['nemerle.server.trace'].enum, ['off', 'messages', 'verbose']);
  assert.equal(properties['nemerle.dotnet.path'].default, 'dotnet');
  assert.equal(properties['nemerle.project'].type, 'string');
  assert.equal(properties['nemerle.projectConfiguration'].default, 'Debug');

  const trust = manifest.capabilities.untrustedWorkspaces;
  assert.equal(trust.supported, 'limited');
  assert.deepEqual(trust.restrictedConfigurations, ['nemerle.server.path', 'nemerle.dotnet.path']);

  // WP-L4: the bundled server is the default, the setting only overrides it,
  // and the VSIX file name always matches the manifest version.
  assert.equal(properties['nemerle.server.path'].default, '');
  assert.match(properties['nemerle.server.path'].markdownDescription, /bundled/u);
  assert.ok(manifest.scripts['package:vsix'].includes(`vscode-nemerle-${manifest.version}.vsix`));
  assert.ok(fs.existsSync(path.join(extensionRoot, 'THIRD-PARTY-NOTICES.md')));
});

// WP-O5a: the server's semantic token legend uses only standard LSP token types
// (so every theme colors them) plus two Nemerle-specific modifiers, which do need
// declaring here. Keep these in sync with SemanticTokenMapping.TokenModifiers.
test('manifest declares the Nemerle semantic token modifiers and their theme fallback', () => {
  const manifest = readJson<Record<string, any>>('package.json');

  const modifiers = manifest.contributes.semanticTokenModifiers.map((entry: { id: string }) => entry.id);
  assert.deepEqual(modifiers, ['quotation', 'escape']);
  for (const entry of manifest.contributes.semanticTokenModifiers) {
    assert.ok(entry.description.length > 0, `${entry.id} needs a description`);
  }

  // Without a scope fallback a custom modifier is invisible in themes that carry
  // no rule for it, which would make the escape/quotation distinction pointless.
  const [scopes] = manifest.contributes.semanticTokenScopes;
  assert.equal(scopes.language, 'nemerle');
  assert.deepEqual(scopes.scopes['string.escape'], ['constant.character.escape']);
  assert.deepEqual(scopes.scopes['*.quotation'], ['meta.embedded']);

  // Semantic highlighting is theme-controlled by default; the whole point of this
  // feature is the macro-keyword coloring, so it is turned on for Nemerle files.
  assert.equal(
    manifest.contributes.configurationDefaults['[nemerle]']['editor.semanticHighlighting.enabled'],
    true,
  );

  // The grammar stays as the fallback for spans the engine does not classify.
  assert.ok(manifest.contributes.grammars.some((grammar: { language: string }) => grammar.language === 'nemerle'));
});

// WP-M6: every test fixture directory must be excluded from the VSIX. These are inputs to the
// test suites, not extension content, and they are easy to miss: `vsce package` reports what it
// included in a tree nobody reads closely, and test-workspace-sdk/ (generated by test/runSdk.ts,
// including its restored obj/) did in fact ship in an intermediate build of this work package.
test('vscodeignore excludes every test workspace from the packaged VSIX', () => {
  const ignore = fs.readFileSync(path.join(extensionRoot, '.vscodeignore'), 'utf8')
    .split(/\r?\n/u)
    .map((line) => line.trim());

  const fixtureDirectories = fs.readdirSync(extensionRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && entry.name.startsWith('test-workspace'))
    .map((entry) => entry.name);
  // The committed one always exists; the generated one only after `npm run test:sdk`, so this
  // additionally pins the rule rather than depending on the directory being present.
  assert.ok(fixtureDirectories.includes('test-workspace'));
  for (const directory of [...new Set([...fixtureDirectories, 'test-workspace', 'test-workspace-sdk'])]) {
    assert.ok(
      ignore.includes(`${directory}/**`),
      `.vscodeignore must exclude ${directory}/** so the fixture never ships to users`,
    );
  }
  assert.ok(ignore.includes('test/**'));
});

test('language configuration provides comments, brackets, closing, surrounding, and indentation', () => {
  const configuration = readJson<Record<string, any>>('language-configuration.json');
  assert.equal(configuration.comments.lineComment, '//');
  assert.deepEqual(configuration.comments.blockComment, ['/*', '*/']);
  assert.ok(configuration.brackets.length >= 4);
  assert.ok(configuration.autoClosingPairs.length >= 6);
  assert.ok(configuration.autoSurroundingPairs.length >= 6);
  assert.equal(typeof configuration.indentationRules.increaseIndentPattern, 'string');
  assert.equal(typeof configuration.indentationRules.decreaseIndentPattern, 'string');
});

function readJson<T>(relativePath: string): T {
  return JSON.parse(fs.readFileSync(path.join(extensionRoot, relativePath), 'utf8')) as T;
}
