import assert from 'node:assert/strict';
import * as path from 'node:path';
import * as vscode from 'vscode';
import type { NemerleExtensionApi } from '../../src/extension';

const extensionId = 'nemerle-project.vscode-nemerle';

const fixedSource = `module SdkProbe
{
  Value() : int
  {
    def value : int = 1;
    value
  }
}
`;

/**
 * WP-M6 acceptance 4: project-aware diagnostics for a project that gets its build logic from
 * the Nemerle.Sdk NuGet package (`<Project Sdk="Nemerle.Sdk.Unofficial/x.y.z">`) instead of an
 * <Import> of the repository's targets.
 *
 * Nothing about the extension is Sdk-aware; what this proves is that the MSBuild project query
 * the whole project-aware pipeline rests on (WP-L2) resolves an SDK from a NuGet feed and
 * evaluates the package's targets, so sources/references/defines reach the engine exactly as
 * they do for a checkout-based project.
 *
 * The workspace this runs against is GENERATED by test/runSdk.ts rather than committed: the
 * project has to pin the SDK version, and that version tracks the compiler generation.
 */
suite('Nemerle extension (Sdk-based project)', () => {
  suiteTeardown(async () => {
    await vscode.commands.executeCommand('workbench.action.closeAllEditors');
  });

  test('applies the Sdk-based project snapshot and reports project-aware diagnostics', async () => {
    const extension = vscode.extensions.getExtension<NemerleExtensionApi>(extensionId);
    assert.ok(extension, 'the Nemerle extension is installed in the test host');
    const api = await extension.activate();

    const uri = vscode.Uri.file(path.join(workspaceRoot(), 'SdkProbe.n'));
    const document = await vscode.workspace.openTextDocument(uri);
    const editor = await vscode.window.showTextDocument(document);
    assert.equal(document.languageId, 'nemerle');

    // The snapshot must come from the package's targets: a query that silently failed would
    // leave the state at 'failed'/'empty' and diagnostics would then only prove single-file
    // analysis, not project-aware analysis.
    await waitUntil(
      () => api.projectStatus?.state === 'applied',
      'the Sdk-based project snapshot to be queried and applied to the engine',
      () => `last status: ${JSON.stringify(api.projectStatus)}`,
    );
    assert.equal(api.projectStatus?.result?.appliedToEngine, true);
    assert.equal(api.projectStatus?.result?.sourceFiles.length, 1);
    assert.match(api.projectStatus?.result?.sourceFiles[0] ?? '', /SdkProbe\.n$/u);

    await waitUntil(
      () => vscode.languages.getDiagnostics(uri).some((diagnostic) =>
        diagnostic.severity === vscode.DiagnosticSeverity.Error),
      'an error diagnostic for the deliberately broken Sdk-based project source',
    );

    await editor.edit((edit) => {
      const all = new vscode.Range(document.positionAt(0), document.positionAt(document.getText().length));
      edit.replace(all, fixedSource);
    });
    assert.equal(document.isDirty, true);
    await waitUntil(
      () => vscode.languages.getDiagnostics(uri).length === 0,
      'diagnostics to clear after the unsaved fix',
    );

    await vscode.commands.executeCommand('workbench.action.revertAndCloseActiveEditor');
  });
});

function workspaceRoot(): string {
  const folder = vscode.workspace.workspaceFolders?.[0];
  assert.ok(folder);
  return folder.uri.fsPath;
}

async function waitUntil(
  predicate: () => boolean,
  description: string,
  diagnose?: () => string,
): Promise<void> {
  const deadline = Date.now() + 60_000;
  while (Date.now() < deadline) {
    if (predicate()) {
      return;
    }
    await new Promise((resolve) => setTimeout(resolve, 200));
  }
  const detail = diagnose ? ` ${diagnose()}` : '';
  assert.fail(`Timed out waiting for ${description}.${detail}`);
}
